FROM solo:latest

COPY . .

##### HEAVY MODEL #####
#CMD ["python3", "tools/train.py", "configs/fish_solov2_r50_fpn_8gpu_3x_v2.py"]
#CMD ["python3", "tools/train.py", "configs/fish_solov2_r50_fpn_8gpu_3x_v2.py", "--autoscale-lr"]
CMD ["python3", "tools/train.py", "configs/fish_solov2_r50_fpn_8gpu_3x_v2.py", "--autoscale-lr", "--resume_from", "work_dirs/solov2_release_r50_fpn_8gpu_3x_v2/latest.pth"]

