FROM solo:latest

COPY . .

##### LIGHT MODELS #####
CMD ["python3", "tools/train.py", "configs/fish_solov2_light_448_r18_fpn_8gpu_3x.py", "--resume_from", "work_dirs/solov2_light_release_r18_fpn_8gpu_3x/epoch_50.pth"]
#CMD ["python3", "tools/train.py", "configs/fish_solov2_light_448_r18_fpn_8gpu_3x.py"]

##### HEAVY MODELS #####
#CMD ["python3", "tools/train.py", "configs/fish_solov2_r50_fpn_8gpu_3x.py"]
